global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spark-application'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'spring-boot-actuator'
    static_configs:
      - targets: ['host.docker.internal:8090']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 15s

  - job_name: 'spark-workers'
    static_configs:
      - targets: ['spark-worker-1:8081', 'spark-worker-2:8082']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 15s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
